/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.umg;

import java.awt.event.ActionEvent;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.JOptionPane;

import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author MAR ACEITUNO
 */
public class Estado_Cuenta extends javax.swing.JFrame {

    /**
     * Creates new form Estado_Cuenta
     */
    public Estado_Cuenta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        N_CuentaField = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("ESTADO DE CUENTA"));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("ESTADOS DE CUENTA");

        jLabel2.setText("NO. CUENTA");

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setText("REGRESAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setText("BUSCAR");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(N_CuentaField, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(207, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(122, 122, 122))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(193, 193, 193)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(N_CuentaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 157, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(114, 114, 114))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GetAccountResume(evt);
            }

            
            }
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Reportes  rp = new Reportes();
          this.setVisible(false);
          rp.setVisible(true);
          
          String N_Cuenta = N_CuentaField.getText();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void GetAccountResume(ActionEvent evt) {
        String NodeCuenta = N_CuentaField.getText();
       // metodo provisional para insertar en el archivo
       try {
        Workbook workbook;
        File file = new File("DatosCuentas.xlsx");
        if (file.exists() && file.length() > 0) {
            workbook = new XSSFWorkbook(new FileInputStream(file));
        } else {
            workbook = new XSSFWorkbook();
        }
        Sheet sheet = workbook.getSheet("Datos de cuentas");
        // Por cada fila, se obtiene la cuarta columna(indice 3), correspondiente al ID de la cuenta
        sheet.forEach((row) -> {
            Cell currentCell = row.getCell(4);
            CellType cellType = currentCell.getCellType();
            double NoCuenta = 0;
            // el switch ayuda a manejar errores por la primera fila de encabezados
            switch (cellType) {
                case CellType.STRING -> {
                    try {
                        NoCuenta = Double.valueOf(currentCell.getStringCellValue());
                        System.out.println("Se encontraron los numeros de cuenta(string): " + currentCell.getStringCellValue());
                        if(Double.valueOf(NodeCuenta) == NoCuenta){
                            System.out.println("Se encontro coincidencia con una cuenta");
                            System.out.println("Indice de fila");
                            System.out.println(currentCell.getRowIndex());
                            Cell currentCellBalance = sheet.getRow(currentCell.getRowIndex()).getCell(3);
                            System.out.println(currentCellBalance.getAddress().formatAsString());
                            System.out.println(currentCellBalance.getStringCellValue());
                            // Se agrega un comentario para la bitacora de datos
                            //String previousComments = row.getCell(7).getRichStringCellValue().toString();
                            FileOutputStream fileOut = new FileOutputStream(String.format("%s.txt",NodeCuenta));
                            File accountDetails = new File(String.format("%s.txt",NodeCuenta));
                            if (accountDetails.exists() && accountDetails.length() > 0) {
                                file.createNewFile();
                            } else {
                                accountDetails.createNewFile();
                            }
                            fileOut = new FileOutputStream(String.format("%s.txt",NodeCuenta), true);
                            fileOut.write((".\nBalance real: " + currentCellBalance.getStringCellValue()).getBytes());
                            fileOut.close();
                            JOptionPane.showMessageDialog(null, "Archivo Excel creado exitosamente.");
                        
                        }
                    } catch (Exception e) {
                        System.out.println("Continuando se encontro una fila que no puede ser convertida a numero");
                        System.out.println(e.getMessage());
                    }
                }
                case CellType.NUMERIC -> {
                    try {
                        NoCuenta = Double.valueOf(currentCell.getStringCellValue());
                        System.out.println("Se encontraron los numeros de cuenta(string): " + currentCell.getStringCellValue());
                        if(Double.valueOf(NodeCuenta) == NoCuenta){
                            System.out.println("Se encontro coincidencia con una cuenta");
                            System.out.println("Indice de fila");
                            System.out.println(currentCell.getRowIndex());
                            Cell currentCellBalance = sheet.getRow(currentCell.getRowIndex()).getCell(2);
                            System.out.println(currentCellBalance.getAddress().formatAsString());
                            System.out.println(currentCellBalance.getStringCellValue());
                            
             
                            System.out.println("Cuenta actualizada");
                            //System.out.println(currentCellBalance.getNumericCellValue());
                            FileOutputStream fileOut = new FileOutputStream("DatosCuentas.xlsx");
                            workbook.write(fileOut);
                            workbook.close();
                            JOptionPane.showMessageDialog(null, "Archivo Excel creado exitosamente.");
                        }
                    } catch (Exception e) {
                        System.out.println("Continuando se encontro una fila que no puede ser convertida a string");
                        System.out.println(e.getMessage());
                    }
                }
                default -> throw new NumberFormatException();
            }
           
        }
        );
    } catch (Exception e) {
        System.out.println("Error en la creacion o lectura del archivo:");
        System.out.println(e.getMessage());
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Estado_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Estado_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Estado_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Estado_Cuenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Estado_Cuenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField N_CuentaField;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
